const express = require('express');
const bodyParser = require('body-parser');
const session = require('express-session');
const memoryStore = new session.MemoryStore;

const app = express();
const authApp = express.Router();

const port = 8082;


// parse request body
app.use(bodyParser());

// CORS
app.use(function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, Content-Type, Accept");
    next();
});

//middleware for logging
app.use(function (req, res, next) {
    const reqUrl = req.protocol + '://' + req.get('host') + req.originalUrl;
    const reqDate = new Date();
    const srcIpAddr = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
    console.log(`${reqDate} Access '${reqUrl}' from ${srcIpAddr}`);
    next();
});

//middleware for session
const sess = {
    secret: 'mysecret',
    resave: false,
    saveUninitialized: false,
    cookie: {maxAge: 1000 * 60 * 60 * 24 * 30},
    store: memoryStore
};

if (app.get('env') === 'production') {
    app.set('trust proxy', 1); // trust first proxy
    sess.cookie.secure = true; // serve secure cookies
}
app.use(session(sess));

//middleware for static pages
app.use(express.static('./'));

//router for basic authentication pages
app.use('/admin', authApp);


app.get('/test', function (req, res) {
    res.send('This is a test!');
});

//provide json api
app.set('json spaces', 2);


app.get('/api', function (req, res) {
    res.json({name: 'John Doe', attr: {age: 30, sex: 'male'}});
});

app.post('/api', function (req, res) {

    const posted = req.body;
    console.log('request body=' + JSON.stringify(posted));

    res.json({name: 'John Doe', attr: {age: 30, sex: 'male'}});
});

app.get('/users/:userId', function (req, res) {
    res.json({name: `John Doe`, userId: `${req.params.userId}`, attr: {age: 30, sex: 'male'}});
});

//provide file
app.get('/file', function (req, res) {
    res.sendFile(__dirname + '/index.html');
});

//provide pages generated by template engine
app.set('view engine', 'pug');
app.set('views', './');
app.get('/pug', function (req, res) {
    res.render('index', {mytitle: 'My Title', mymessage: 'Hi, Pug!'});
});

//provide session page
app.get('/counter', function (req, res, next) {
    console.log(req.session.counter);
    if (req.session.counter) {
        req.session.counter++;
    } else {
        req.session.counter = 1;
    }

    res.send(`<html><body><p>${req.session.counter}</p>
              <p>expires in:${req.session.cookie.maxAge / 1000}s</p></body></html>`);
});

app.get('/*', function (req, res) {
    res.send('<html><body><h1>Others</h1></body></html>');
});


//provide basic-auth pages
const basicAuth = require('basic-auth');
authApp.use(function (req, res, next) {
    const credentials = basicAuth(req);
    if (!credentials || (credentials.name !== 'admin' || credentials.pass !== 'mypassword')) {
        const REALM = 'secure!';
        res.header('WWW-Authenticate', 'Basic realm="' + REALM + '"').status(401).end('Access denied');
    } else {
        next();
    }
});

authApp.get('/test', function (req, res) {
    res.send('<html><body><h1>Auth Page</h1></body></html>');
});

authApp.get('/*', function (req, res) {
    res.send('<html><body><h1>Others in auth page</h1></body></html>');
});

app.listen(port, () => {
    console.log('Server started on port:' + port);
});

